FROM python:3.12-slim
LABEL authors="Aeneas Tews"

WORKDIR /mesa_designer

RUN apt-get update && apt-get install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN chmod +x ./docker_entrypoint.sh

RUN pip install -r requirements.txt

RUN python3 ./setup.py

EXPOSE 8501
EXPOSE 8000

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["./docker_entrypoint.sh"]