FROM python:3.13.7-slim
LABEL authors="Aeneas Tews"

WORKDIR /mesa_designer

RUN apt update && apt upgrade -y && apt install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY .streamlit ./.streamlit
COPY api ./api
COPY dependencies ./dependencies
COPY resources ./resources
COPY util ./util
COPY .dockerignore LICENSE requirements.txt setup.py ./

RUN pip install -r requirements.txt

RUN python3 ./setup.py

EXPOSE 8000

HEALTHCHECK CMD curl --fail http://localhost:8000/_stcore/health

ENTRYPOINT ["uvicorn",  "--host",  "0.0.0.0", "api.main:app"]