FROM python:3.12-slim
LABEL authors="Aeneas Tews"

WORKDIR /mesa_designer

RUN apt-get update && apt-get install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install -r requirements.txt

RUN python3 ./setup.py

EXPOSE 8000

HEALTHCHECK CMD curl --fail http://localhost:8000/_stcore/health

ENTRYPOINT ["uvicorn",  "--host",  "0.0.0.0", "api.main:app"]