FROM python:3.13.7-slim
LABEL authors="Aeneas Tews"

WORKDIR /mesa_designer

RUN apt update && apt upgrade -y && apt install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY .streamlit ./.streamlit
COPY app ./app
COPY dependencies ./dependencies
COPY resources ./resources
COPY util ./util
COPY .dockerignore LICENSE requirements.txt setup.py ./

RUN pip install -r requirements.txt

RUN python3 ./setup.py

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]