name: Docker rebuild

on:
  workflow_call:
#  workflow_dispatch:

jobs:
  rebuild:
    runs-on: self-hosted
    steps:
      # Step 1: Docker rebuild
      - name: Docker rebuild
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            docker compose build --no-cache
            docker compose up --force-recreate --detach
